bot/urls.py
from django.urls import path

from . import views

app_name = 'bot'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('add-translation', views.AddTranslation.as_view(), name='add_translation'),
]

events/urls.py
from django.urls import path

from . import views

app_name = 'events'
urlpatterns = [
    path('upload-rounds/', views.RoundUploadView.as_view(), name='upload_rounds'),
    path('upload-rubrics/', views.RubricUploadView.as_view(), name='upload_rubrics'),
    path('report/', views.ReportsView.as_view(), name='reports_page'),
    path('close-round/', views.CloseRound.as_view(), name='close_round'),
    path('get_summary_report/<int:round_id>/<int:competition_id>/<slug:action>', views.SummaryReportView.as_view(), name='summary_report'),
    path('send_report/', views.send_report_ajax, name='send_report'),
    path('ajax-calls/get-report-status/', views.get_report_status, name='get_report_status'),
]

judges/urls.py
from django.urls import path

from . import views

app_name = 'judges'
urlpatterns = [
    path('', views.index, name='index'),
    path('createJudge/', views.CreateJudge.as_view(), name='createJudge')
]

projects/urls.py
from django.urls import path

from . import views

app_name = 'projects'
urlpatterns = [
    path('', views.index, name='index'),
]

templates/main/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    {% load static %}
    <link rel="stylesheet" href='{% static "rate_web/css/main_style.css" %}'>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>WRO admin panel</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css"
          integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=Ubuntu"/>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    <script src="{% static 'rate_web/js/jquery-3.3.1.min.js' %}"></script>

    <title>WRO rate bot</title>
</head>

<body class="fixed-nav sticky-footer bg-dark" id="page-top">
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top" id="mainNav">
    <a class="navbar-brand" href="/">JuryBot Manager</a>
    <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse"
            data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false"
            aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav navbar-sidenav" id="exampleAccordion">
            <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Link">
                <a class="nav-link" href="{% url 'index' %}">
                    <i class="fa fa-fw fa-cogs"></i>
                    <span class="nav-link-text">Events</span>
                </a>
            </li>
            <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Components">
                <a class="nav-link nav-link-collapse collapsed" data-toggle="collapse" href="#mangeComponents"
                   data-parent="#manageAccordion">
                    <i class="fa fa-fw fa-wrench"></i>
                    <span class="nav-link-text">Manage users</span>
                </a>
                <ul class="sidenav-second-level collapse" id="mangeComponents">
                    <li>
                        <a href="{% url 'judges:index' %}">Judges</a>
                    </li>
                    <li>
                        <a href="{% url 'projects:index' %}">Projects</a>
                    </li>
                </ul>
            </li>
            <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Link">
                <a class="nav-link" href="{% url 'events:reports_page' %}">
                    <i class="fa fa-fw fa-table"></i>
                    <span class="nav-link-text">Overall report</span>
                </a>
            </li>
            <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Link">
                <a class="nav-link" href="{% url 'bot:index' %}">
                    <i class="fa fa-fw fa-cogs"></i>
                    <span class="nav-link-text">Bot</span>
                </a>
            </li>
            <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Link">
                <a class="nav-link" target="_blank" href="/admin">
                    <i class="fa fa-database"></i>
                    <span class="nav-link-text">Complex admin panel</span>
                </a>
            </li>
        </ul>
        <ul class="navbar-nav sidenav-toggler">
            <li class="nav-item">
                <a class="nav-link text-center" id="sidenavToggler">
                    <i class="fa fa-fw fa-angle-left"></i>
                </a>
            </li>
        </ul>
    </div>
</nav>

<div class="content-wrapper">


    {% block content %}

    {% endblock %}

    {% if messages %}
        {% include 'modals/messages.html' %}
    {% endif %}
    <!-- /.container-fluid-->
    <!-- /.content-wrapper-->
    <footer class="sticky-footer">
        <div class="container">
            <div class="text-center">
                <small>Copyright © Innopolis 2018</small>
            </div>
        </div>
    </footer>
</div>

<script src="http://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
        integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"
        integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T"
        crossorigin="anonymous"></script>

</body>

</html>