bot/urls.py
from django.urls import path

from . import views

app_name = 'bot'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('add-translation', views.AddTranslation.as_view(), name='add_translation'),
]

bot/models.py
from django.db import models

# Create your models here.

bot/forms.py
from django.forms import ModelForm

from labels.models import Labels
from parler.forms import TranslatableModelForm


class AddLangForm(TranslatableModelForm):
    class Meta:
        model = Labels
        fields = '__all__'

bot/views.py
from django.contrib import messages
from django.core.files.storage import FileSystemStorage
from django.shortcuts import reverse, HttpResponseRedirect
from django.utils.translation.trans_real import get_supported_language_variant
from django.views.generic import FormView

from labels.models import Labels
from scripts.parse_labels import parse_labels
from .forms import AddLangForm


class AddTranslation(FormView):
    form_class = AddLangForm
    template_name = 'bot/index.html'

    def form_valid(self, form):
        lang_code = self.request.POST.get('lang_code')
        try:
            get_supported_language_variant(lang_code)
        except BaseException as e:
            messages.warning(self.request, 'Invalid language code specified: {0}'.format(str(e)))
            return HttpResponseRedirect(reverse('bot:index'))

        if Labels.objects.exists():
            labels_object = Labels.objects.first()
        else:
            labels_object = Labels()

        labels_object.set_current_language(lang_code)
        for attr, value in form.cleaned_data.items():
            setattr(labels_object, attr, value)
        labels_object.save()
        return super().form_valid(form)

    def get_success_url(self):
        lang_code = self.request.POST.get('lang_code')
        return reverse('bot:index') + '?lang_code={}'.format(lang_code)


class IndexView(FormView):
    form_class = AddLangForm
    template_name = 'bot/index.html'
    extra_context = dict()

    def post(self, request, *args, **kwargs):
        if len(request.FILES) != 0 and (request.FILES['labels_json']):
            labels_file = request.FILES['labels_json']
            fs = FileSystemStorage()
            filename = fs.save('translation_uploads/' + labels_file.name, labels_file)
            f = fs.open(filename)
            try:
                parse_labels(f)
                lang_code = Labels.objects.first().get_current_language()
                return HttpResponseRedirect(reverse('bot:index') + '?lang_code={0}'.format(lang_code))
            except BaseException as e:
                messages.error(request, 'Error while parsing Bot Translations file: <br> {}'.format(str(e)))

        return HttpResponseRedirect(reverse('bot:index'))

    def get_form(self, form_class=None, lang_code=None):
        if Labels.objects.exists():
            labels_object = Labels.objects.first()
            if lang_code is not None:
                labels_object.set_current_language(lang_code)
            return self.form_class(instance=labels_object)
        else:
            return self.form_class()

    def get_languages(self):
        if Labels.objects.exists():
            labels_object = Labels.objects.first()
            languages = labels_object.get_available_languages()
            return languages

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        lang_code = self.request.GET.get('lang_code')

        if lang_code is None:
            lang_code = ''
            form = self.get_form_class()
            context.update({'form': form})
        else:
            try:
                form = self.get_form(lang_code=lang_code)
            except BaseException as e:
                lang_code = ''
                form = self.get_form_class()
            context.update({'form': form})

        context.update({'languages': self.get_languages(), 'lang_code': lang_code})
        context.update(self.extra_context)
        return context

    def dispatch(self, request, *args, **kwargs):
        lang_code = self.request.GET.get('lang_code')
        if lang_code is not None:
            try:
                get_supported_language_variant(lang_code)
            except BaseException as e:
                messages.warning(self.request, 'Invalid language code specified: {0}'.format(str(e)))

        return super(IndexView, self).dispatch(request, *args, **kwargs)

templates/bot/index.html
{% extends 'main/base.html' %}

{% block content %}
    <div class="row">
        <div class="col-sm-4">
            <div class="container">
                <div style="margin-top: 100px;">
                    <h2 style="margin: 20px 5px">Upload json</h2>
                    <form method="post" enctype="multipart/form-data" class="row p-3" id="uplaod_form">
                        {% csrf_token %}
                        <div class="col-md-10 custom-file" id="customFile" lang="es">
                            <input type="file" name="labels_json" class="custom-file-input"
                                   style="cursor: pointer;"
                                   id="inputFile"
                                   aria-describedby="fileHelp" required>
                            <label class="custom-file-label sot-file-label" for="inputFile" id="inputFile_label">
                                Select file...
                            </label>
                        </div>
                        <div class="col-sm-12 col-md-2">
                            <button type="submit" class="btn btn-outline-primary mt-3 mt-md-0" form="uplaod_form">
                                upload
                            </button>
                        </div>
                    </form>
                    {% if file_parse_status %}
                        <h1 style="color: lightgreen; margin-top: 60px; width: 100%; text-align: center; height: 60px">
                            File was succesfully parsed</h1>
                        <div style="width: max-content; margin: auto">
                            <h3>Token list:</h3>
                            {% if token_list %}
                                {% for token in token_list %}
                                    {{ token }} <br>
                                {% endfor %}
                            {% endif %}
                        </div>
                    {% endif %}
                </div>
                <div>
                    {% if languages %}
                        <h2 style="margin-top: 20px">or select item to modify</h2>
                        <div class="list-group" style="width: max-content; min-width: 30%; margin-top: 20px">
                            {% for lang_item in languages %}
                                <a href="{% url 'bot:index' %}?lang_code={{ lang_item }}"
                                   class="list-group-item list-group-item-action">
                                    <h5>Lang code: {{ lang_item }}</h5>
                                </a>
                            {% endfor %}
                        </div>
                    {% endif %}
                </div>
            </div>
        </div>
        <div class="col-sm-8">
            <h2 style="margin: 20px 50px">Create new language translation</h2>
            {% load i18n widget_tweaks %}
            <form class="form-horizontal" role="form" method="post" action="{% url 'bot:add_translation' %}">
                {% csrf_token %}
                <div class="form-group">
                    <label class="col-sm-12 control-label" for="id_lang_code">Language code</label>
                    <div class="col-sm-12">
                        <input id="id_lang_code" type="text" name="lang_code" class="form-control"
                               value="{{ lang_code }}" required>
                    </div>
                </div>
                {% for field in form %}
                    {% if field.errors %}
                        <div class="form-group has-error">
                            <label class="col-sm-2 control-label" for="id_{{ field.name }}">{{ field.label }}</label>
                            <div class="col-sm-10">
                                {{ field|attr:"class:form-control" }}
                                <span class="help-block">
                                            {% for error in  field.errors %}{{ error }}{% endfor %}
                                        </span>
                            </div>
                        </div>
                    {% else %}
                        <div class="form-group">
                            <label class="col-sm-12 control-label" for="id_{{ field.name }}">{{ field.label }}</label>
                            <div class="col-sm-12">
                                {{ field|attr:"class:form-control" }}
                                {% if field.help_text %}
                                    <p class="help-block">
                                        <small>{{ field.help_text }}</small>
                                    </p>
                                {% endif %}
                            </div>
                        </div>
                    {% endif %}
                {% endfor %}
                <div class="form-group">
                    <div class="col-sm-offset-2 col-sm-10">
                        <button type="submit" class="btn btn-lg btn-success">Add/modify</button>
                    </div>
                </div>
                {% if success %}
                    <div class="alert alert-success">
                        <strong>Success: </strong> Judge was successfully added!
                    </div>
                    <h3>Token:</h3>
                    {% if token %}
                        {{ token }}
                        <hr>
                    {% endif %}
                {% endif %}
                {% if not success and error %}
                    <div class="alert alert-danger">
                        <strong>Error: </strong> {{ error }}.
                    </div>
                {% endif %}
            </form>
        </div>
    </div>

    <script>
        $('.custom-file-input').on('change', function () {
            let fileName = document.getElementById("inputFile").files[0].name;
            $(this).next('.custom-file-label').html(fileName);
        });
    </script>
{% endblock %}