bot/urls.py
from django.urls import path

from . import views

app_name = 'bot'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('add-translation', views.AddTranslation.as_view(), name='add_translation'),
]

events/urls.py
from django.urls import path

from . import views

app_name = 'events'
urlpatterns = [
    path('upload-rounds/', views.RoundUploadView.as_view(), name='upload_rounds'),
    path('upload-rubrics/', views.RubricUploadView.as_view(), name='upload_rubrics'),
    path('report/', views.ReportsView.as_view(), name='reports_page'),
    path('close-round/', views.CloseRound.as_view(), name='close_round'),
    path('get_summary_report/<int:round_id>/<int:competition_id>/<slug:action>', views.SummaryReportView.as_view(), name='summary_report'),
    path('send_report/', views.send_report_ajax, name='send_report'),
    path('ajax-calls/get-report-status/', views.get_report_status, name='get_report_status'),
]

templates/modals/close_round_modal.html
{% load static %}
    <div id="RoundCloseModal" class="modal fade" tabindex="-1" role="dialog">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Are you sure you want to close this round?</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <p id="close_round_title">Could not get round name. Try again later</p>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-light" data-dismiss="modal">
                        <i class="fa fa-ban" style="color: black;"></i> Cancel
                    </button>
                    <button type="submit" form="close_round_form" style="color: #F44336" onclick="sot_delete_all({{ skill.id }})" class="btn btn-light">
                        <i class="fa fa-check"></i> Yes, close
                    </button>
                    <form id="close_round_form" action="{% url 'events:close_round' %}" method="post">
                        {% csrf_token %}
                        <input hidden name="round_id" value="1">
                    </form>
                </div>
            </div>
        </div>
    </div>

templates/modals/messages.html
{% load static %}
{% block content %}
    {% for message in messages %}
        <div class="alert alert-{{ message.tags }} alert-dismissible"
             style="position: fixed; right: 10px; bottom: 10px; min-width: 400px; max-width: 90vw; z-index: 40"
             role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span
                    aria-hidden="true">&times;</span></button>
            <strong>{% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}Error{% else %}
                {{ message.tags|title }}{% endif %}!</strong> {% autoescape off %} {{ message }} {% endautoescape %}
        </div>
    {% endfor %}
{% endblock %}