bot/urls.py
from django.urls import path

from . import views

app_name = 'bot'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('add-translation', views.AddTranslation.as_view(), name='add_translation'),
]

events/urls.py
from django.urls import path

from . import views

app_name = 'events'
urlpatterns = [
    path('upload-rounds/', views.RoundUploadView.as_view(), name='upload_rounds'),
    path('upload-rubrics/', views.RubricUploadView.as_view(), name='upload_rubrics'),
    path('report/', views.ReportsView.as_view(), name='reports_page'),
    path('close-round/', views.CloseRound.as_view(), name='close_round'),
    path('get_summary_report/<int:round_id>/<int:competition_id>/<slug:action>', views.SummaryReportView.as_view(), name='summary_report'),
    path('send_report/', views.send_report_ajax, name='send_report'),
    path('ajax-calls/get-report-status/', views.get_report_status, name='get_report_status'),
]

events/models.py
from django.db import models

from criterions.models import Criterion
from judges.models import Judge
from projects.models import Competition
from projects.models import Project
from workloads.models import Round
from enum import Enum


# Create your models here.


class JudgeReports(models.Model):
    token = models.CharField(max_length=40)
    ready = models.BooleanField(default=False)
    time = models.DateTimeField()
    progress = models.FloatField(default=0)
    filepath = models.CharField(max_length=200)
    round = models.ForeignKey(Round, on_delete=models.CASCADE)
    competition = models.ForeignKey(Competition, on_delete=models.CASCADE)


class TeamReport(models.Model):
    token = models.CharField(max_length=40)
    ready = models.BooleanField(default=False)
    time = models.DateTimeField()
    progress = models.FloatField(default=0)
    filepath = models.CharField(max_length=200)
    round = models.ForeignKey(Round, on_delete=models.CASCADE, null=True)
    all_rounds = models.BooleanField()


"""
    Transactions
    Table that stores all the actions made by the users
    id|judge|initial_state|resulting_state|project|criterion|media_action|media|api_response|value|timestamp
"""


class State(Enum):
    NULL = 0  # Null state. Returned from db when user not found
    ACTIVATED = 1 # Activated
    TK_WAIT = 4  # Start Regular (Token Request)
    TK_CHECK = 6  # Token Check
    TK_WRONG = 8  # Token Checked Request Wrong (Token wrong -> request New Token)
    MENU = 10  # Initial state after token validated
    ARCHIVE = 12  # Archive
    SETTINGS = 13  # Settings
    EVALUATION = 20  # This state is required for evaluation, but the settings are disabled


class Transactions(models.Model):
    judge = models.ForeignKey(Judge, on_delete=models.DO_NOTHING)
    initial_state = models.IntegerField(default=State.NULL.value)
    resulting_state = models.IntegerField(blank=True)
    project = models.ForeignKey(Project, on_delete=models.DO_NOTHING, blank=True)
    criterion = models.ForeignKey(Criterion, on_delete=models.DO_NOTHING, blank=True)
    api_response = models.TextField(blank=True)
    value = models.TextField(blank=True)
    timestamp = models.DateTimeField(auto_now=True)

    class Meta:
        db_table = 'events_transaction'

events/views.py
import datetime
import json
import os
import secrets
import ssl
import threading

import base58
import pytz
from django.conf import settings
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Q
from django.shortcuts import HttpResponse, Http404, redirect
from django.urls import reverse
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import View, TemplateView

from criterions.utils import get_rubrics
from projects.models import Project, Competition
from scripts import get_evaluation_report
from scripts.get_judges_report import get_judges_report
from scripts.get_teams_report import get_teams_report
from scripts.support_scripts import to_latin
from workloads.models import Round
from .models import JudgeReports, TeamReport
from .utils import parse_events, parse_rubrics

ssl._create_default_https_context = ssl._create_unverified_context


class Index(LoginRequiredMixin, TemplateView):
    template_name = 'events/events.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        try:
            context['rubrics'] = get_rubrics()
        except BaseException as e:
            messages.error(self.request, 'Can not get rubrics.<br>{}'.format(str(e)))
        context['today'] = datetime.datetime.now(pytz.timezone(settings.TIME_ZONE))

        context['rounds_list'] = Round.objects.all()
        return context


class CloseRound(LoginRequiredMixin, View):
    def post(self, request, *args, **kwargs):
        try:
            round_id = self.request.POST.get('round_id')
            round_obj = Round.objects.get(id=round_id)
            round_obj.end_timestamp = datetime.datetime.now(pytz.timezone(settings.TIME_ZONE))
            round_obj.save()
        except BaseException as e:
            messages.error(self.request, 'Error: {error_msg}'.format(error_msg=str(e)))
        return redirect(reverse('index'))


class RoundUploadView(LoginRequiredMixin, View):

    def post(self, request, *args, **kwargs):
        try:
            parse_events(request.FILES['rounds_json'])
            messages.success(self.request, 'Events file was successfully parsed.')
        except BaseException as e:
            messages.error(self.request, 'Error while parsing Events file: <br> {}'.format(str(e)))
        return redirect(reverse('index'))


class SummaryReportView(View):

    def post(self, request, *args, **kwargs):
        output_type = request.POST.get('output_type')
        anonymous = request.POST.get('anonymous') is not None
        filename = get_evaluation_report.get_report_data(self.kwargs['round_id'], self.kwargs['competition_id'],
                                                         output_type, anonymous)
        if filename:
            if self.kwargs['action'] == 'download':
                return send_report(filename, settings.BASE_DIR + settings.MEDIA_FOLDERS['summary_reports'])
            else:
                return redirect('{}/{}'.format(settings.MEDIA_FOLDERS['summary_reports'], filename))
        else:
            return redirect('{}/not_evaluated.pdf'.format(settings.STATIC_FOLDERS['summary_reports']))


class RubricUploadView(LoginRequiredMixin, View):

    def post(self, request, *args, **kwargs):
        try:
            parse_rubrics(request.FILES['rubrics_json'])
            messages.success(self.request, 'Rubrics file was successfully parsed.')
        except BaseException as e:
            messages.error(self.request, 'Error while parsing Rubrics file: <br> {}'.format(str(e)))
        return redirect(reverse('index'))


class ReportsView(LoginRequiredMixin, TemplateView):
    template_name = 'report/report.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        today = datetime.datetime.now(pytz.timezone(settings.TIME_ZONE))
        rounds = Round.objects.filter(Q(start_timestamp__lte=today))
        competitions = []
        projects = Project.objects.all()
        for project_item in projects:
            if project_item.competition not in competitions:
                competitions.append(project_item.competition)
        judges_ready_reports = reversed(JudgeReports.objects.all().order_by('time'))
        teams_ready_reports = reversed(TeamReport.objects.all().order_by('time'))
        context.update({'rounds': rounds,
                        'today': today,
                        'competitions': competitions,
                        'judges_ready_reports': judges_ready_reports,
                        'teams_ready_reports': teams_ready_reports})
        return context

    def post(self, request, *args, **kwargs):
        report_type = request.POST.get('type')
        today = datetime.datetime.today()
        token = generate_token(15)
        output_type = request.POST.get('output_type')
        print(request.POST.get('dpi'))
        dpi = max(min(int(request.POST.get('dpi') or 500), 500), 20)
        if report_type == 'judge':
            round_id = request.POST.get('round_id')
            competition_id = request.POST.get('competition_id')
            round_item = Round.objects.get(id=round_id)
            competition_item = Competition.objects.get(id=competition_id)
            judge_report_db = JudgeReports(token=token, ready=False, time=today, filepath='empty',
                                           competition=competition_item, round=round_item)
            judge_report_db.save()
            judge_report(round_id=round_id, competition_id=competition_id, token=token, output_type=output_type,
                         dpi=dpi)
        elif report_type == 'team':
            round_id = request.POST.get('round_id')
            round_id = int(round_id)
            all_rounds = False
            if round_id == 0:
                all_rounds = True
                round_item = None
            else:
                round_item = Round.objects.get(id=round_id)

            team_report_db = TeamReport(token=token, round=round_item, ready=False, time=today, filepath='empty',
                                        all_rounds=all_rounds)
            team_report_db.save()
            team_report(round_id=round_id, token=token, output_type=output_type, dpi=dpi)

        context = self.get_context_data()
        return super(TemplateView, self).render_to_response(context)


@csrf_exempt
@login_required
def get_report_status(request):
    token = request.GET.get('token')
    report_type = request.GET.get('type')
    if token is not None:
        if report_type == 'judge':
            judge_db = JudgeReports.objects.get(token=token)
            return HttpResponse(json.dumps({'progress': int(judge_db.progress * 100)}))
        elif report_type == 'team':
            team_db = TeamReport.objects.get(token=token)
            return HttpResponse(json.dumps({'progress': int(team_db.progress * 100)}))
    return HttpResponse('Error: ', status=400)


# Judge report
def judge_report(round_id, competition_id, token, output_type, dpi):
    t = threading.Thread(target=get_judges_report, args=(round_id, competition_id, token, output_type, dpi))
    t.setDaemon(True)
    t.start()


# Team report
def team_report(round_id, token, output_type, dpi):
    t = threading.Thread(target=get_teams_report, args=(round_id, token, output_type, dpi))
    t.setDaemon(True)
    t.start()


def send_report(filename, dir_name):
    full_path = '{}/{}'.format(dir_name, filename)
    if os.path.exists(full_path):
        zip_file = open(full_path, 'rb')
        response = HttpResponse(zip_file, content_type='application/force-download')
        response['Content-Disposition'] = 'attachment; filename={}'.format(filename)
        return response
    else:
        raise Http404


@csrf_exempt
@login_required
def send_report_ajax(request):
    filepath = request.POST.get('filepath')
    dir_name = os.path.dirname(filepath)
    filename = os.path.basename(filepath)
    full_path = '{}/{}'.format(dir_name, filename)
    if os.path.exists(full_path):
        zip_file = open(full_path, 'rb')
        response = HttpResponse(zip_file, content_type='application/force-download')
        response['Content-Disposition'] = 'attachment; filename={}'.format(
            to_latin(os.path.splitext(filename)[0]) + '.zip')
        return response
    else:
        raise Http404


def generate_token(length):
    return base58.b58encode(secrets.token_bytes(length)).decode("utf-8")

templates/events/create_event.html
{% extends 'main/base.html' %}

{% block content %}
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12">
                <!-- Example Bar Chart Card-->
                <div class="card mb-3">
                    <div class="card-header">
                        <i class="fa fa-list-ul"></i> Create event:
                    </div>
                    <div class="card-body">


                        {% load static %}


                            <form method="post" enctype="multipart/form-data">
                                {% csrf_token %}
                                <input type="file" name="myfile">
                                <button type="submit">Upload</button>
                            </form>
                            {% if file_parse_status %}
                                <h1 style="color: lightgreen; margin-top: 60px; width: 100%; text-align: center; height: 60px">
                                    File was succesfully parsed</h1>
                                <div style="width: max-content; margin: auto">
                                    <h3>Token list:</h3>
                                    {% if token_list %}
                                        {% for token in token_list %}
                                            {{ token }} <br>
                                        {% endfor %}
                                    {% endif %}
                                </div>
                            {% endif %}
                        <hr>
                    </div>
                    <div class="card-footer small text-muted">Updated yesterday at 11:59 PM</div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/events/create_event_error.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<div>
    <h1>ERROR:</h1>
    <h3> Bad XML</h3>
</div>
</body>
</html>

templates/events/create_rubric.html
{% extends 'main/base.html' %}

{% block content %}
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12">
                <!-- Example Bar Chart Card-->
                <div class="card mb-3">
                    <div class="card-header">
                        <i class="fa fa-list-ul"></i> Create rubric:
                    </div>
                    <div class="card-body">


                        {% load static %}

                        <form method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            <input type="file" name="myfile">
                            <button type="submit">Upload</button>
                        </form>
                        {% if file_parse_status %}
                            <h1 style="color: lightgreen; margin-top: 60px; width: 100%; text-align: center; height: 60px">
                                File was succesfully parsed</h1>
                        {% endif %}
                        <hr>
                    </div>
                    <div class="card-footer small text-muted">Updated yesterday at 11:59 PM</div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

templates/events/events.html
{% extends 'main/base.html' %}

{% block content %}
    {% include 'modals/close_round_modal.html' %}

    <div class="container-fluid" style="margin-bottom: 50px;">
        <div class="row">
            <div class="col-lg-12">
                <!-- Example Bar Chart Card-->
                <div class="card mb-3">
                    <div class="card-header">
                        <i class="fa fa-list-ul"></i> Rubrics:
                        <div style="float: right">
                            <form action="{% url 'events:upload_rubrics' %}"
                                  method="post" enctype="multipart/form-data" class="row">
                                {% csrf_token %}
                                <label class="col text-center mt-2" for="customFile">Upload json</label>
                                <div class="col-md-7 custom-file" id="customFile" lang="es">
                                    <input type="file" name="rubrics_json" class="rubrics-file-input"
                                           style="cursor: pointer;"
                                           id="rubrics_input_file"
                                           aria-describedby="fileHelp" required>
                                    <label class="custom-file-label sot-file-label" for="rubrics_input_file"
                                           id="rubrics_input_label">
                                        Select file...
                                    </label>
                                </div>
                                <div class="col-sm-12 col-md-2">
                                    <button type="submit"
                                            class="btn btn-outline-primary mt-3 mt-md-0">
                                        upload
                                    </button>
                                </div>
                            </form>
                        </div>
                    </div>
                    <div class="card-body">
                        {% if rubrics %}
                            <div class="animated fadeIn" style="margin: -20px">
                                <div class="row">
                                    <div class="card-body">
                                        {% for rubric, value in rubrics.items %}
                                            <div class="accordion" id="accordion2">
                                                <div class="accordion-group">
                                                    <div class="accordion-heading">
                                                        <a class="accordion-toggle" data-toggle="collapse"
                                                           data-target="#collapseOne{{ forloop.counter }}"
                                                           href="#collapseOne{{ forloop.counter }}">
                                                            <button class="btn btn-lg btn-outline-dark"
                                                                    style="width: 100%; height: 45px; margin-bottom: 10px">
                                                                <h5>{{ rubric }}</h5></button>
                                                        </a>
                                                    </div>
                                                    <div id="collapseOne{{ forloop.counter }}"
                                                         class="accordion-body collapse in" style="margin-top: 10px">
                                                        <div class="accordion-inner">
                                                            {% for group, value in value.items %}
                                                                <table id="bootstrap-data-table"
                                                                       style="margin: 20px 0 20px 100px; width: 60%; min-width: 400px"
                                                                       class="table table-striped table-bordered">
                                                                    <h3 style="margin-left: 50px">{{ group }}</h3>
                                                                    <tbody>
                                                                    <td><h5 style="color: gray; text-align: center">
                                                                        Criterions</h5></td>
                                                                    {% for criterion in value %}
                                                                        <tr>
                                                                            <td>{{ criterion.title }}</td>
                                                                        </tr>
                                                                    {% endfor %}
                                                                    </tbody>
                                                                </table>
                                                            {% endfor %}
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        {% endfor %}
                                    </div>
                                </div>
                            </div>
                        {% else %}
                            <p>No rubrics here.</p>
                        {% endif %}
                    </div>
                    <div class="card-footer small text-muted">Updated yesterday at 11:59 PM</div>
                </div>
            </div>
        </div>
    </div>

    <div class="container-fluid" style="margin-bottom: 50px">
        <div class="row">
            <div class="col-lg-12">
                <!-- Example Bar Chart Card-->
                <div class="card mb-3">
                    <div class="card-header">
                        <i class="fa fa-list-ul"></i> Rounds:
                        <div style="float: right;">
                            <form action="{% url 'events:upload_rounds' %}"
                                  method="post" enctype="multipart/form-data" class="row">
                                {% csrf_token %}
                                <label class="col text-center mt-2" for="customFile">Upload json</label>
                                <div class="col-md-7 custom-file" id="customFile" lang="es">
                                    <input type="file" name="rounds_json" class="events-file-input"
                                           style="cursor: pointer;"
                                           id="events_input_file"
                                           aria-describedby="fileHelp" required>
                                    <label class="custom-file-label sot-file-label" for="events_input_file"
                                           id="events_input_label">
                                        Select file...
                                    </label>
                                </div>
                                <div class="col-sm-12 col-md-2">
                                    <button type="submit"
                                            class="btn btn-outline-primary mt-3 mt-md-0">
                                        upload
                                    </button>
                                </div>
                            </form>
                        </div>
                    </div>
                    <div class="card-body">
                        {% if rounds_list %}
                            <div class="animated fadeIn">
                                <div class="row">
                                    <div class="card-body" style="margin: -20px">
                                        <table id="bootstrap-data-table" class="table table-striped table-bordered">
                                            <thead>
                                            <tr>
                                                <th>Id</th>
                                                <th>Title</th>
                                                <th>Start time</th>
                                                <th>End Time</th>
                                                <th>Action</th>
                                            </tr>
                                            </thead>
                                            <tbody>
                                            {% for round in rounds_list %}
                                                <tr>
                                                    <td>{{ round.id }}</td>
                                                    <td>{{ round.title }}</td>
                                                    <td>{{ round.start_timestamp }}</td>
                                                    <td>{{ round.end_timestamp }}</td>
                                                    <td>
                                                        {% if round.end_timestamp <= today %}
                                                            <i class="fa fa-calendar-check-o"
                                                               style="color: #ef5350"></i>
                                                            <span> Closed at <br><b>{{ round.end_timestamp }}</b></span>
                                                        {% else %}
                                                            <button class="btn btn-outline-danger"
                                                                    onclick="set_modal_info('{{ round.title }}', {{ round.id }})"
                                                                    data-toggle="modal" data-target="#RoundCloseModal">
                                                                <i class="fa fa-hourglass-end"></i>
                                                                Close
                                                            </button>
                                                        {% endif %}
                                                    </td>
                                                </tr>
                                            {% endfor %}
                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                            </div>
                        {% else %}
                            <p>No rounds here.</p>
                        {% endif %}
                    </div>
                    <div class="card-footer small text-muted">Updated yesterday at 11:59 PM</div>
                </div>
            </div>
        </div>
    </div>

    <script>
        $('.events-file-input').on('change', function () {
            let fileName = document.getElementById("events_input_file").files[0].name;
            $(this).next('#events_input_label').html(fileName);
        });

        $('.rubrics-file-input').on('change', function () {
            let fileName = document.getElementById("rubrics_input_file").files[0].name;
            $(this).next('#rubrics_input_label').html(fileName);
        });

        function set_modal_info(name, id) {
            $('#close_round_title').html(`Round <b>"${name}"</b> will be closed`);
            $('input[name="round_id"]').val(id);
        }
    </script>
{% endblock %}